primitivo = (input('Digite algo: '))
print('O tipo primitivo desse valor é: {}'.format(type(primitivo)))
print('Possui somente espaços?: {}'.format(primitivo.isspace()))
print('Possui somente numeros?: {}'.format(primitivo.isnumeric()))
print('Possui somente letras?: {}'.format(primitivo.isalpha()))
print('Possui somente letras ou numeros?: {}'.format(primitivo.isalnum()))
print('Possui somente letras maiúsculas?: {}'.format(primitivo.isupper()))
print('Possui somente letras minúsculas?: {}'.format(primitivo.islower()))
print('Possui capitalização: {}'.format(primitivo.istitle()))
